spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/my-mobile?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
        username: root
        password: Opel9005@
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
        defer-datasource-initialization: true
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    sql:
        init:
            mode: never

mail:
    host: localhost
    port: 1025
    username: admin@example.com
    password: ""

management:
    endpoints:
        web:
            exposure:
                include: "*"
    prometheus:
        metrics:
            export:
                enabled: true

server:
    port: 8060

    spring:
        thymeleaf:
            enabled: true
            prefix: classpath:/templates/
            suffix: .html
            mode: HTML
            cache: false
            encoding: UTF-8


mymobile:
    admin:
        defaultpass: ${DEFAULT_PASS:test}
